##########################################
##### h2 connection ######################
##########################################
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
######## SHOW SQL ##################################
    show-sql: true
    properties:
      hibernate:
        format_sql: true
########## LOGGING ###################################
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace